import Testing
@testable import KeyCat

@Suite("MarkdownExporter Tests")
struct MarkdownExporterTests {

    @Test("Exports single app with categories")
    func singleApp() {
        let files = [
            ShortcutFile(
                app: "TestApp",
                prefix: nil,
                icon: nil,
                categories: [
                    ShortcutCategory(name: "General", shortcuts: [
                        Shortcut(key: "Ctrl+s", desc: "Save"),
                        Shortcut(key: "Ctrl+q", desc: "Quit")
                    ])
                ]
            )
        ]

        let result = MarkdownExporter.export(files: files)
        #expect(result.contains("# KeyCat 단축키 치트시트"))
        #expect(result.contains("## TestApp"))
        #expect(result.contains("### General"))
        #expect(result.contains("| `Ctrl+s` | Save |"))
        #expect(result.contains("| `Ctrl+q` | Quit |"))
    }

    @Test("Includes prefix when present")
    func prefixIncluded() {
        let files = [
            ShortcutFile(
                app: "tmux",
                prefix: "Ctrl+b",
                icon: nil,
                categories: [
                    ShortcutCategory(name: "Panes", shortcuts: [
                        Shortcut(key: "%", desc: "Split vertical")
                    ])
                ]
            )
        ]

        let result = MarkdownExporter.export(files: files)
        #expect(result.contains("> Prefix: `Ctrl+b`"))
    }

    @Test("Exports multiple apps")
    func multipleApps() {
        let files = [
            ShortcutFile(app: "App1", prefix: nil, icon: nil, categories: [
                ShortcutCategory(name: "Cat1", shortcuts: [
                    Shortcut(key: "a", desc: "action a")
                ])
            ]),
            ShortcutFile(app: "App2", prefix: nil, icon: nil, categories: [
                ShortcutCategory(name: "Cat2", shortcuts: [
                    Shortcut(key: "b", desc: "action b")
                ])
            ])
        ]

        let result = MarkdownExporter.export(files: files)
        #expect(result.contains("## App1"))
        #expect(result.contains("## App2"))
    }

    @Test("Exports empty files array")
    func emptyFiles() {
        let result = MarkdownExporter.export(files: [])
        #expect(result.contains("# KeyCat 단축키 치트시트"))
        #expect(result.contains("Generated by KeyCat"))
    }

    @Test("Escapes pipe characters in table")
    func escapesPipes() {
        let files = [
            ShortcutFile(app: "Test", prefix: nil, icon: nil, categories: [
                ShortcutCategory(name: "Cat", shortcuts: [
                    Shortcut(key: "a|b", desc: "pipe|test")
                ])
            ])
        ]

        let result = MarkdownExporter.export(files: files)
        #expect(result.contains("a\\|b"))
        #expect(result.contains("pipe\\|test"))
    }

    @Test("Contains table headers")
    func tableHeaders() {
        let files = [
            ShortcutFile(app: "Test", prefix: nil, icon: nil, categories: [
                ShortcutCategory(name: "Cat", shortcuts: [
                    Shortcut(key: "x", desc: "action")
                ])
            ])
        ]

        let result = MarkdownExporter.export(files: files)
        #expect(result.contains("| 단축키 | 설명 |"))
        #expect(result.contains("|--------|------|"))
    }
}
