import AppKit

enum MarkdownExporter {
    static func export(files: [ShortcutFile]) -> String {
        var lines: [String] = []
        lines.append("# KeyCat 단축키 치트시트")
        lines.append("")

        for file in files {
            lines.append("## \(file.app)")
            if let prefix = file.prefix {
                lines.append("> Prefix: `\(prefix)`")
            }
            lines.append("")

            for category in file.categories {
                lines.append("### \(category.name)")
                lines.append("")
                lines.append("| 단축키 | 설명 |")
                lines.append("|--------|------|")
                for shortcut in category.shortcuts {
                    let key = shortcut.key
                        .replacingOccurrences(of: "|", with: "\\|")
                    let desc = shortcut.desc
                        .replacingOccurrences(of: "|", with: "\\|")
                    lines.append("| `\(key)` | \(desc) |")
                }
                lines.append("")
            }
        }

        lines.append("---")
        lines.append("*Generated by KeyCat*")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    static func saveWithPanel(content: String, suggestedName: String = "keycat-cheatsheet") {
        let panel = NSSavePanel()
        panel.title = "치트시트 내보내기"
        panel.nameFieldStringValue = "\(suggestedName).md"
        panel.allowedContentTypes = [.plainText]
        panel.canCreateDirectories = true

        guard panel.runModal() == .OK, let url = panel.url else { return }

        do {
            try content.write(to: url, atomically: true, encoding: .utf8)
            NSWorkspace.shared.open(url)
        } catch {
            let alert = NSAlert()
            alert.messageText = "내보내기 실패"
            alert.informativeText = error.localizedDescription
            alert.runModal()
        }
    }
}
